spring:
  application:
    name: ead-notification-service
  output:
    ansi:
      enabled: Always
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configserver
      password: 'ead123cs'