server:
  port: 8084

spring:
  application:
    name: ead-notification-service
  output:
    ansi:
      enabled: Always

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
